version: '3'
services:
  app:
    image: "node:16-slim"
    working_dir: /app
    command: bash -c "npm install && npm run dev"
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
