version: '3'

networks:
  my_network:

services:
  frontend:
    build:
      context: .
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    restart: always
    networks:
      - my_network

  backend:
    build:
      context: ./backend
    env_file:
      - backend/.env
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    depends_on:
      - db
    restart: always
    networks:
      - my_network

  db:
    image: mysql:8.0.33-debian
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - backend/.env
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always
    networks:
      - my_network

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    networks:
      - my_network
